/*
   Copyright 2010 Massachusetts General Hospital

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */
package org.sc.probro.data;

import java.io.*;
import java.lang.reflect.*;
import java.util.*;
import java.util.Date;
import java.sql.*;

import org.sc.probro.data.DBObject;

public class MetadataObject extends DBObject {
	
	/*
metadata_id      int not null primary key generated by default as identity,
request_id       int not null references REQUESTS(request_id) ON DELETE CASCADE,
metadata_key     varchar(100) not null,
metadata_value   varchar(1000) not null,
created_on       date not null,
created_by       int not null references USERS(user_id) ON DELETE CASCADE
	 */
	
	public Integer metadata_id;
	public Integer request_id;
	public String metadata_key, metadata_value;
	public Date created_on;
	public Integer created_by;
	
	public MetadataObject() { super(); }
	public MetadataObject(ResultSet rs) throws SQLException { super(rs); }
	
	public boolean isAutoGenerated(String fieldName) {
		return fieldName.equals("metadata_id");
	}
	
	public String toString() { 
		return String.format("%d:%s=\"%s\"", request_id, metadata_key, metadata_value);
	}
	
	public String[] getAutoGeneratedFields() {
		return new String[] { "metadata_id" };
	}
	
	public String[] getKeyFields() {
		return getAutoGeneratedFields();
	}
}
