/*
	Copyright 2010 Massachusetts General Hospital

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/
package org.sc.probro.data;

import java.io.*;
import java.lang.reflect.*;
import java.util.*;
import java.sql.*;

import org.sc.probro.Ontology;
import org.sc.probro.data.DBObject;

public class OntologyObject extends DBObject {
	
	public Integer ontology_id;
	public String ontology_name; 
	public Integer maintainer_id;
	
	public OntologyObject() { super(); }
	public OntologyObject(ResultSet rs) throws SQLException { super(rs); }
	
	public boolean isAutoGenerated(String fieldName) {
		return fieldName.toLowerCase().equals("ontology_id");
	}

	public String getKey() { return "ontology_id"; }
	
	public String[] getAutoGeneratedFields() {
		return new String[] { "ontology_id" };
	}
	
	public String[] getKeyFields() {
		return getAutoGeneratedFields();
	}
}
