package org.sc.probro.data;

import java.io.*;
import java.lang.reflect.*;
import java.util.*;
import java.sql.*;

import org.sc.probro.data.DBObject;

public class Ontology extends DBObject {
	
	public Integer ontology_id;
	public String name; 
	
	public Ontology() { super(); }
	public Ontology(ResultSet rs) throws SQLException { super(rs); }
	
	public boolean isAutoGenerated(String fieldName) {
		return fieldName.toLowerCase().equals("ontology_id");
	}

	public String getKey() { return "ontology_id"; }
}
