package org.sc.probro.data;

import java.io.*;
import java.lang.reflect.*;
import java.util.*;
import java.sql.*;

import org.sc.probro.data.DBObject;

public class ProvisionalTermObject extends DBObject {
	
	public Integer request_id;
	public Integer provisional_id;
	public String provisional_term;
	
	public ProvisionalTermObject() { super(); }
	public ProvisionalTermObject(ResultSet rs) throws SQLException { super(rs); }
	
	public boolean isAutoGenerated(String fieldName) {
		return fieldName.equals("provisional_id");
	}

	public String getKey() { return "provisional_id"; }
	
	public String[] getAutoGeneratedFields() {
		return getKeyFields();
	}
	
	public String[] getKeyFields() {
		return new String[]{ "provisional_id" };
	}
}
