package org.sc.probro.data;

import java.io.*;
import java.lang.reflect.*;
import java.util.*;
import java.sql.*;

import org.sc.probro.data.DBObject;

public class User extends DBObject {
	
	public Integer user_id;
	public String user_name;
	
	public User() { super(); }
	public User(ResultSet rs) throws SQLException { super(rs); }
	
	public boolean isAutoGenerated(String fieldName) {
		return fieldName.toLowerCase().equals("user_id");
	}
	
	public String getKey() { return "user_id"; }

}
