package org.sc.probro.data;

import java.io.*;
import java.lang.reflect.*;
import java.util.*;
import java.sql.*;

import org.sc.probro.data.DBObject;

public class UserObject extends DBObject {
	
	public Integer user_id;
	public String user_name;
	
	public UserObject() { super(); }
	public UserObject(ResultSet rs) throws SQLException { super(rs); }
	
	public boolean isAutoGenerated(String fieldName) {
		return fieldName.toLowerCase().equals("user_id");
	}
	
	public String getKey() { return "user_id"; }
	
	public String[] getAutoGeneratedFields() {
		return new String[] { "user_id" };
	}
	
	public String[] getKeyFields() {
		return getAutoGeneratedFields();
	}
}
